// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-lx4nLNG7ZtQgghb3XF0uRR_dXZyJ5pg',
    appId: '1:763530750987:web:d9fa4fe08713c9bcc2ab0e',
    messagingSenderId: '763530750987',
    projectId: 'promiapp-45c92',
    authDomain: 'promiapp-45c92.firebaseapp.com',
    storageBucket: 'promiapp-45c92.firebasestorage.app',
    measurementId: 'G-0VYTEJVTGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2qjwod6zHtl6l0BoNP8H0qTo5HHsYBIs',
    appId: '1:763530750987:android:489631145e7d6136c2ab0e',
    messagingSenderId: '763530750987',
    projectId: 'promiapp-45c92',
    storageBucket: 'promiapp-45c92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5v6lbLqr7m1PNp9My54g1eb-F8MVmCjY',
    appId: '1:763530750987:ios:8b9e3f76f4234ec9c2ab0e',
    messagingSenderId: '763530750987',
    projectId: 'promiapp-45c92',
    storageBucket: 'promiapp-45c92.firebasestorage.app',
    iosBundleId: 'com.example.promi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5v6lbLqr7m1PNp9My54g1eb-F8MVmCjY',
    appId: '1:763530750987:ios:8b9e3f76f4234ec9c2ab0e',
    messagingSenderId: '763530750987',
    projectId: 'promiapp-45c92',
    storageBucket: 'promiapp-45c92.firebasestorage.app',
    iosBundleId: 'com.example.promi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-lx4nLNG7ZtQgghb3XF0uRR_dXZyJ5pg',
    appId: '1:763530750987:web:e20ba34079907184c2ab0e',
    messagingSenderId: '763530750987',
    projectId: 'promiapp-45c92',
    authDomain: 'promiapp-45c92.firebaseapp.com',
    storageBucket: 'promiapp-45c92.firebasestorage.app',
    measurementId: 'G-GKVVZ55BHN',
  );
}
